#!/bin/bash
# set -e
# echo "THE PG USER IS ${POSTGRES_USER}"
# echo "THE POSTGRES_DB is ${POSTGRES_DB}"
# echo "THE POSTGRES_PASSWORD is ${POSTGRES_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER synapse;
    ALTER USER synapse WITH PASSWORD '${POSTGRES_PASSWORD}';
    CREATE DATABASE synapse;
    GRANT ALL PRIVILEGES ON DATABASE synapse TO synapse;
EOSQL
