version: '3'

services:
  synapse:
    # image: docker.io/matrixdotorg/synapse:v1.63.0
    build:
      context: .
      dockerfile: ./docker/synapse/Dockerfile
      args:
        SERVER_NAME: 'rbpops.co.uk'
        REPORT_STATS: 'no'
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    # volumes:
      # - synapse_data:/data
      # - ./data:/data:rw,Z   #use this once we've got generated files working
    env_file:
      - ./envs/synapse
    depends_on:
      - synapse_db
    ports:
      - 8008:8008


  synapse_db:
    # image: docker.io/postgres:14-alpine
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    restart: unless-stopped
    environment:
      # - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse_db_data:/var/lib/postgresql/synapse_data

volumes:
  synapse_data:
  synapse_db_data:
