---
applications:
- name: delivery-unit-matrix
  memory: 2048M
  instances: 1
  env:
    SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
  disk_quota: 2048M
  services:
    - delivery-unit-matrix-postgres
  routes:
  - route: delivery-unit-matrix.london.cloudapps.digital
    protocol: http1
  health-check-type: port
