---
applications:
- name: synapse-sandbox
  memory: 1024M
  instances: 1
  env:
    SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
  disk_quota: 2048M
  services:
    - synapse-postgres-sandbox
  routes:
  - route: synapse-sandbox.london.cloudapps.digital
    protocol: http1
  health-check-type: port
