---
applications:
- name: synapse-postgres-sandbox
  host: synapse-postgres-sandbox
  # buildpacks:
  # - https://github.com/cloudfoundry/staticfile-buildpack.git
  routes:
  - route: synapse-postgres-sandbox.apps.internal
    protocol: http2
  stack: cflinuxfs3
  # command: bash ./app-start.sh
  env:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   POSTGRES_USER: synapse
  #   POSTGRES_PASSWORD: mysecretpassword
  #   POSTGRES_DB: synapse
  # services:
  # - my-postgres-db
