name: Deploy Element Web App

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - sandbox
      - develop
      - prod

  release:
    types: [published]

permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read

jobs:
  push_images:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io
      ENVIRONMENT: ${{ github.ref_name }}
      SERVER_NAME: synapse-${{ github.ref_name }}.london.cloudapps.digital
      REPORT_STATS: 'no'

    strategy:
      matrix:
        app: [element]
        include:
          - app: element
            dockerfile: docker/element/Dockerfile

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup prod servername
        if:  ${{ github.ref_name == 'prod'}}
        run: echo "SERVER_NAME=delivery-group-matrix.london.cloudapps.digital" >> $GITHUB_ENV

      - name: Build, tag, and push ${{ matrix.app }} image
        env:
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}

        run: |
          docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --build-arg SERVER_NAME=$SERVER_NAME
          docker push -a $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE

  deploy_image:
    needs: [push_images]

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io

    strategy:
      matrix:
        app: [element]

    steps:
      - uses: actions/checkout@v3

      - name: Get non-prod space name
        if:  ${{ github.event_name != 'release' }}
        uses: kanga333/variable-mapper@v0.2.2
        with:
          key: "${{github.ref_name}}"
          map: |
            {
              "sandbox": {"CF_SPACE": "sandbox"},
              "develop": {"CF_SPACE": "develop"},
              "prod": {"CF_SPACE": "prod"},
              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
            }

      - name: Download CF CLI
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: CF push element
        if:  ${{ github.ref_name != 'prod' }}
        env:
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}
          PAT_TOKEN_USER: ${{ secrets.PAT_TOKEN_USER }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push -f manifests/"$CF_SPACE"/${{ matrix.app }}_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER

      - name: CF push ${{ matrix.app }}
        if:  ${{ github.ref_name == 'prod' }}
        env:
          DOCKER_FILE: ${{ matrix.dockerfile }}
          DOCKER_IMAGE: ${{ matrix.app }}
          PAT_TOKEN_USER: ${{ secrets.PAT_TOKEN_USER }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push -f manifests/"$CF_SPACE/${{ matrix.app }}"_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER
